### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by starakaj** [BarnesFoundation/barnes-tms-extract#15]
It's super out of date, especially with respect to what one needs to do to get up and running

**Comment by micahwalter** [comment]
Would be good to list out all the actual dependencies vs. optional things like image processing services. I tried to set this up on my machine and I think it required Anaconda to be installed, which seems like its probably only required if I want to process images myself, right?

Is there an npm command to just run the site vs. the additional services?

-m

**Comment by starakaj** [comment]
Yeah, you'll definitely need miniconda at least to get up and running. There is no command to run the dashboard site without specific services, but it should be possible. The TMS export, Elasticsearch and image processing are all separate services after all. I'll make a ticket for that.

**Comment by thisisaaronland** [comment]
Is there a boxes and arrows diagram of all the moving pieces?

**Comment by starakaj** [comment]
Yes, it's at `misc/ARCHITECTURE.png`. Also you can run `npm run docs` for jsdoc documentation, which should include that boxes and arrows diagram but doesn't, yet.

**Comment by thisisaaronland** [comment]
Yeah, I meant something a lot more detailed. For example there is nothing in that diagram that talks about Seneca. Like... what is Seneca even and what does it do / what is its relationship to the other pieces ?

**Comment by micahwalter** [comment]
FYI There were some warnings at the end of the `npm install` on Ubuntu 16.10.

```
ubuntu@ubuntu-yakkety:/vagrant/projects/CollectionWebsite$ npm install

> collection-website@0.0.1 postinstall /vagrant/projects/CollectionWebsite
> git submodule update --remote --recursive && node src/scripts/pythonenv.js

/bin/bash
Creating tmsdiff Python environment
/bin/bash: conda: command not found
Installing python dependencies
/bin/bash: activate: No such file or directory
Collecting cffi==1.9.1 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 1))
  Using cached cffi-1.9.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting click==6.7 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 2))
  Using cached click-6.7-py2.py3-none-any.whl
Collecting cryptography==1.7.1 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 3))
  Using cached cryptography-1.7.1.tar.gz
Collecting csvdiff==0.3.1 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 4))
  Using cached csvdiff-0.3.1-py2.py3-none-any.whl
Collecting enum34==1.1.6 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 5))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting functools32==3.2.3.post2 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 6))
Collecting idna==2.2 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 7))
  Using cached idna-2.2-py2.py3-none-any.whl
Collecting ipaddress==1.0.18 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 8))
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting jsonschema==2.6.0 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 9))
  Using cached jsonschema-2.6.0-py2.py3-none-any.whl
Collecting pyasn1==0.1.9 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 10))
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pycosat==0.6.1 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 11))
Collecting pycparser==2.17 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 12))
Collecting pyOpenSSL==16.2.0 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 13))
  Using cached pyOpenSSL-16.2.0-py2.py3-none-any.whl
Collecting requests==2.12.4 (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 14))
  Using cached requests-2.12.4-py2.py3-none-any.whl
Requirement already satisfied: six==1.10.0 in /usr/local/lib/python2.7/dist-packages (from -r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 15))
Requirement already satisfied: setuptools>=11.3 in /usr/lib/python2.7/dist-packages (from cryptography==1.7.1->-r /vagrant/projects/CollectionWebsite/src/py_csv_diff/requirements.txt (line 3))
Building wheels for collected packages: cryptography
  Running setup.py bdist_wheel for cryptography: started
  Running setup.py bdist_wheel for cryptography: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0buNoO/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpfZ_kKbpip-wheel- --python-tag cp27:
  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-0buNoO/cryptography/setup.py", line 334, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 348, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 394, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 851, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1123, in best_match
      return self.obtain(req, installer)
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1135, in obtain
      return installer(requirement)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 461, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 689, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 719, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 900, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1139, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1127, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0buNoO/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-0buNoO/cryptography/setup.py", line 334, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 348, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 394, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 851, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1123, in best_match
      return self.obtain(req, installer)
    File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1135, in obtain
      return installer(requirement)
    File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 461, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 689, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 719, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 900, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1139, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1127, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed cleaning build dir for cryptography
Failed to build cryptography
Installing collected packages: pycparser, cffi, click, idna, pyasn1, enum34, ipaddress, cryptography, functools32, jsonschema, csvdiff, pycosat, pyOpenSSL, requests
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pycparser'
Deactivating python source
/bin/bash: deactivate: No such file or directory
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
```
